language: node_js
node_js:
  - "0.10"
  - "0.12"
env: DEBUG=dynamodel*
before_script:
  - npm install -g gulp
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_2015-01-27.tar.gz
  - tar xfz dynamodb_local_2015-01-27.tar.gz
  - java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory &

